// Generated by gencpp from file xju_pnc/xju_taskRequest.msg
// DO NOT EDIT!


#ifndef XJU_PNC_MESSAGE_XJU_TASKREQUEST_H
#define XJU_PNC_MESSAGE_XJU_TASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xju_pnc
{
template <class ContainerAllocator>
struct xju_taskRequest_
{
  typedef xju_taskRequest_<ContainerAllocator> Type;

  xju_taskRequest_()
    : type(0)
    , command(0)
    , dir()
    , path_name()  {
    }
  xju_taskRequest_(const ContainerAllocator& _alloc)
    : type(0)
    , command(0)
    , dir(_alloc)
    , path_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dir_type;
  _dir_type dir;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_name_type;
  _path_name_type path_name;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(EXECUTE)
  #undef EXECUTE
#endif
#if defined(_WIN32) && defined(RECORD)
  #undef RECORD
#endif
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(PAUSE)
  #undef PAUSE
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(KEEP_TEACH)
  #undef KEEP_TEACH
#endif
#if defined(_WIN32) && defined(KEEP_COVER_ZZ)
  #undef KEEP_COVER_ZZ
#endif
#if defined(_WIN32) && defined(KEEP_COVER_BS)
  #undef KEEP_COVER_BS
#endif
#if defined(_WIN32) && defined(DISCARD)
  #undef DISCARD
#endif

  enum {
    EXECUTE = 0u,
    RECORD = 1u,
    START = 0u,
    PAUSE = 1u,
    STOP = 2u,
    KEEP_TEACH = 1u,
    KEEP_COVER_ZZ = 2u,
    KEEP_COVER_BS = 3u,
    DISCARD = 4u,
  };


  typedef boost::shared_ptr< ::xju_pnc::xju_taskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xju_pnc::xju_taskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct xju_taskRequest_

typedef ::xju_pnc::xju_taskRequest_<std::allocator<void> > xju_taskRequest;

typedef boost::shared_ptr< ::xju_pnc::xju_taskRequest > xju_taskRequestPtr;
typedef boost::shared_ptr< ::xju_pnc::xju_taskRequest const> xju_taskRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xju_pnc::xju_taskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xju_pnc::xju_taskRequest_<ContainerAllocator1> & lhs, const ::xju_pnc::xju_taskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.command == rhs.command &&
    lhs.dir == rhs.dir &&
    lhs.path_name == rhs.path_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xju_pnc::xju_taskRequest_<ContainerAllocator1> & lhs, const ::xju_pnc::xju_taskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xju_pnc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xju_pnc::xju_taskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xju_pnc::xju_taskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xju_pnc::xju_taskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cf93950e008686c2a8d49fc8c652466";
  }

  static const char* value(const ::xju_pnc::xju_taskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cf93950e008686cULL;
  static const uint64_t static_value2 = 0x2a8d49fc8c652466ULL;
};

template<class ContainerAllocator>
struct DataType< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xju_pnc/xju_taskRequest";
  }

  static const char* value(const ::xju_pnc::xju_taskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 EXECUTE = 0\n"
"uint8 RECORD = 1\n"
"\n"
"uint8 START = 0\n"
"uint8 PAUSE = 1\n"
"uint8 STOP = 2\n"
"\n"
"uint8 KEEP_TEACH = 1\n"
"uint8 KEEP_COVER_ZZ = 2\n"
"uint8 KEEP_COVER_BS = 3\n"
"uint8 DISCARD = 4\n"
"\n"
"uint8 type #EXECUTE RECORD\n"
"uint8 command #START PAUSE STOP KEEP_TEACH KEEP_COVER DISCARD\n"
"string dir\n"
"string path_name\n"
;
  }

  static const char* value(const ::xju_pnc::xju_taskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.command);
      stream.next(m.dir);
      stream.next(m.path_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xju_taskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xju_pnc::xju_taskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xju_pnc::xju_taskRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dir);
    s << indent << "path_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XJU_PNC_MESSAGE_XJU_TASKREQUEST_H
