// Generated by gencpp from file costmap_plugins/keepOutZoneResponse.msg
// DO NOT EDIT!


#ifndef COSTMAP_PLUGINS_MESSAGE_KEEPOUTZONERESPONSE_H
#define COSTMAP_PLUGINS_MESSAGE_KEEPOUTZONERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace costmap_plugins
{
template <class ContainerAllocator>
struct keepOutZoneResponse_
{
  typedef keepOutZoneResponse_<ContainerAllocator> Type;

  keepOutZoneResponse_()
    : id(0)  {
    }
  keepOutZoneResponse_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct keepOutZoneResponse_

typedef ::costmap_plugins::keepOutZoneResponse_<std::allocator<void> > keepOutZoneResponse;

typedef boost::shared_ptr< ::costmap_plugins::keepOutZoneResponse > keepOutZoneResponsePtr;
typedef boost::shared_ptr< ::costmap_plugins::keepOutZoneResponse const> keepOutZoneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator1> & lhs, const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator1> & lhs, const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace costmap_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "309d4b30834b338cced19e5622a97a03";
  }

  static const char* value(const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x309d4b30834b338cULL;
  static const uint64_t static_value2 = 0xced19e5622a97a03ULL;
};

template<class ContainerAllocator>
struct DataType< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costmap_plugins/keepOutZoneResponse";
  }

  static const char* value(const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"\n"
;
  }

  static const char* value(const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keepOutZoneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costmap_plugins::keepOutZoneResponse_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTMAP_PLUGINS_MESSAGE_KEEPOUTZONERESPONSE_H
