// Generated by gencpp from file costmap_plugins/keepOutZone.msg
// DO NOT EDIT!


#ifndef COSTMAP_PLUGINS_MESSAGE_KEEPOUTZONE_H
#define COSTMAP_PLUGINS_MESSAGE_KEEPOUTZONE_H

#include <ros/service_traits.h>


#include <costmap_plugins/keepOutZoneRequest.h>
#include <costmap_plugins/keepOutZoneResponse.h>


namespace costmap_plugins
{

struct keepOutZone
{

typedef keepOutZoneRequest Request;
typedef keepOutZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct keepOutZone
} // namespace costmap_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::costmap_plugins::keepOutZone > {
  static const char* value()
  {
    return "b77ce4a77ca03e6be1804558a2836ebc";
  }

  static const char* value(const ::costmap_plugins::keepOutZone&) { return value(); }
};

template<>
struct DataType< ::costmap_plugins::keepOutZone > {
  static const char* value()
  {
    return "costmap_plugins/keepOutZone";
  }

  static const char* value(const ::costmap_plugins::keepOutZone&) { return value(); }
};


// service_traits::MD5Sum< ::costmap_plugins::keepOutZoneRequest> should match
// service_traits::MD5Sum< ::costmap_plugins::keepOutZone >
template<>
struct MD5Sum< ::costmap_plugins::keepOutZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::costmap_plugins::keepOutZone >::value();
  }
  static const char* value(const ::costmap_plugins::keepOutZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::costmap_plugins::keepOutZoneRequest> should match
// service_traits::DataType< ::costmap_plugins::keepOutZone >
template<>
struct DataType< ::costmap_plugins::keepOutZoneRequest>
{
  static const char* value()
  {
    return DataType< ::costmap_plugins::keepOutZone >::value();
  }
  static const char* value(const ::costmap_plugins::keepOutZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::costmap_plugins::keepOutZoneResponse> should match
// service_traits::MD5Sum< ::costmap_plugins::keepOutZone >
template<>
struct MD5Sum< ::costmap_plugins::keepOutZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::costmap_plugins::keepOutZone >::value();
  }
  static const char* value(const ::costmap_plugins::keepOutZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::costmap_plugins::keepOutZoneResponse> should match
// service_traits::DataType< ::costmap_plugins::keepOutZone >
template<>
struct DataType< ::costmap_plugins::keepOutZoneResponse>
{
  static const char* value()
  {
    return DataType< ::costmap_plugins::keepOutZone >::value();
  }
  static const char* value(const ::costmap_plugins::keepOutZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COSTMAP_PLUGINS_MESSAGE_KEEPOUTZONE_H
